-- =============================================================================
-- Migration: 20260322000003_orders_and_messages.sql
-- Description: Orders, order_items, and messages tables with auto-generated
--              order number trigger, full index sets, and RLS policies for
--              buyer/vendor/admin access control.
-- Project: Primeserve Facility Solutions
-- Depends on: 20260322000001_core_enums_and_users.sql
--               (order_status, payment_status ENUMs; users table;
--                update_updated_at_column())
--             20260322000002_products_table.sql
--               (products table)
-- Created: 2026-03-22
--
-- TABLE OVERVIEW
--
--   orders       — One order per buyer-vendor pair per checkout session.
--                  Tracks lifecycle from 'pending' through 'delivered'.
--                  Never deleted — ON DELETE RESTRICT on both buyer_id and
--                  vendor_id so financial records survive account deletion.
--
--   order_items  — Line items belonging to an order. Stores a snapshot of the
--                  product name and SKU at the time of purchase so the order
--                  remains accurate even if the vendor later edits the product.
--
--   messages     — Simple buyer ↔ vendor inbox tied (optionally) to an order.
--                  Supports the pre-order enquiry and post-order support flows.
--
-- KEY DESIGN DECISIONS
--
-- 1. order_number format: PS-ORD-XXXXXX
--    Human-readable identifier shown in emails, invoices, and dashboards.
--    Auto-generated by generate_order_number() with a collision-safe loop.
--    Format: "PS-ORD-" + 6 random uppercase alphanumeric characters.
--    Stored as TEXT UNIQUE so it can be searched/filtered without joins.
--
-- 2. ON DELETE RESTRICT for buyer_id and vendor_id
--    Orders are financial records. If a buyer or vendor account is deleted,
--    the orders must be retained for audit and legal purposes.
--    RESTRICT prevents the deletion entirely — the admin must archive the
--    user first and then decide what to do with their orders.
--
-- 3. order_items.product_name is a SNAPSHOT
--    If a vendor renames a product after an order is placed, the order_items
--    row must still show the name the buyer saw at checkout. Storing the name
--    (and SKU) as plain columns — not just the FK — achieves this. The FK
--    to products(id) is kept for joining but uses ON DELETE RESTRICT so
--    a vendor cannot delete a product that has been ordered.
--
-- 4. messages.order_id is nullable (ON DELETE SET NULL)
--    Messages can exist before an order (pre-sale enquiry) or after
--    the order is archived. Setting order_id to NULL on order deletion
--    keeps the message history intact without orphaning the row.
--
-- 5. Partial index on messages(is_read) WHERE is_read = FALSE
--    The unread-message badge in the UI only needs to count/filter
--    unread rows. A partial index on the false subset is much smaller
--    and faster than a full index on a boolean column.
-- =============================================================================


-- =============================================================================
-- SECTION 1: ORDER NUMBER AUTO-GENERATION FUNCTION
-- Runs BEFORE INSERT on orders. Generates a PS-ORD-XXXXXX identifier using
-- 6 random uppercase alphanumeric characters. Loops until a unique value is
-- found (collision probability is negligible at MVP scale but handled
-- correctly for production safety).
-- =============================================================================

-- Drop any partial objects from a previous failed run
DROP TABLE IF EXISTS messages    CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders      CASCADE;
DROP FUNCTION IF EXISTS generate_order_number();

CREATE OR REPLACE FUNCTION generate_order_number()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  chars     TEXT    := 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  suffix    TEXT    := '';
  candidate TEXT;
  i         INTEGER;
BEGIN
  -- Only auto-generate if the caller did not supply an order_number
  IF NEW.order_number IS NOT NULL AND NEW.order_number <> '' THEN
    RETURN NEW;
  END IF;

  LOOP
    -- Build a 6-character random uppercase alphanumeric suffix
    suffix := '';
    FOR i IN 1..6 LOOP
      suffix := suffix || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;

    candidate := 'PS-ORD-' || suffix;

    -- Exit the loop once we have a candidate not already in the table
    EXIT WHEN NOT EXISTS (SELECT 1 FROM orders WHERE order_number = candidate);
  END LOOP;

  NEW.order_number := candidate;
  RETURN NEW;
END;
$$;

COMMENT ON FUNCTION generate_order_number() IS
  'BEFORE INSERT trigger: auto-generates a unique PS-ORD-XXXXXX order number. '
  'Uses 6 random uppercase alphanumeric chars. Loops until no collision. '
  'Skipped when the caller supplies a non-empty order_number.';


-- =============================================================================
-- SECTION 2: ORDERS TABLE
-- =============================================================================

CREATE TABLE orders (
  -- -----------------------------------------------------------------------
  -- Identity
  -- -----------------------------------------------------------------------
  id               UUID           PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable order reference shown on invoices and in emails.
  -- Format: PS-ORD-XXXXXX. Auto-generated by trigger if not supplied.
  order_number     TEXT           UNIQUE NOT NULL,

  -- -----------------------------------------------------------------------
  -- Parties
  -- -----------------------------------------------------------------------

  -- The buyer who placed the order. RESTRICT prevents deleting a buyer who
  -- has orders — financial records must be preserved.
  buyer_id         UUID           NOT NULL REFERENCES users(id) ON DELETE RESTRICT,

  -- The vendor fulfilling the order. RESTRICT for the same reason.
  vendor_id        UUID           NOT NULL REFERENCES users(id) ON DELETE RESTRICT,

  -- -----------------------------------------------------------------------
  -- Lifecycle status
  -- -----------------------------------------------------------------------

  -- Order lifecycle: pending → confirmed → processing → shipped → delivered
  -- Cancellation path: any pre-shipped status → cancelled
  -- See order_status enum in Migration 1 for all valid values.
  status           order_status   DEFAULT 'pending',

  -- Payment lifecycle: pending → paid → refunded / failed
  -- See payment_status enum in Migration 1 for all valid values.
  payment_status   payment_status DEFAULT 'pending',

  -- -----------------------------------------------------------------------
  -- Financials (all amounts in INR)
  -- -----------------------------------------------------------------------

  -- Sum of (unit_price × quantity) for all line items, before GST and shipping.
  subtotal         DECIMAL(12,2)  NOT NULL DEFAULT 0,

  -- Total GST collected across all line items.
  -- Sum of order_items.gst_amount for this order.
  gst_amount       DECIMAL(12,2)  NOT NULL DEFAULT 0,

  -- Flat shipping charge for the order. Zero for free-shipping orders.
  shipping_amount  DECIMAL(12,2)  DEFAULT 0,

  -- Grand total: subtotal + gst_amount + shipping_amount.
  -- Stored denormalised for fast retrieval on dashboards and invoices.
  total_amount     DECIMAL(12,2)  NOT NULL DEFAULT 0,

  -- -----------------------------------------------------------------------
  -- Addresses (stored as JSONB snapshots at checkout time)
  -- Snapshot approach: if the buyer later updates their profile address,
  -- the order still reflects where it was actually shipped/billed.
  --
  -- Expected keys for both address fields:
  --   { "name": str, "line1": str, "line2": str|null, "city": str,
  --     "state": str, "pincode": str, "phone": str }
  -- -----------------------------------------------------------------------
  shipping_address JSONB          NOT NULL,

  -- Billing address. Defaults to shipping_address at the API layer if not
  -- separately provided by the buyer.
  billing_address  JSONB,

  -- -----------------------------------------------------------------------
  -- Optional metadata
  -- -----------------------------------------------------------------------

  -- Free-text notes from the buyer (e.g. "Please deliver before 10 AM").
  notes            TEXT,

  -- Reason provided when status is set to 'cancelled'.
  -- Populated by the API when a buyer or vendor cancels the order.
  cancelled_reason TEXT,

  -- Timestamp set by the API when status transitions to 'delivered'.
  delivered_at     TIMESTAMPTZ,

  -- -----------------------------------------------------------------------
  -- Timestamps
  -- -----------------------------------------------------------------------
  created_at       TIMESTAMPTZ    DEFAULT NOW(),
  updated_at       TIMESTAMPTZ    DEFAULT NOW()
);


-- =============================================================================
-- SECTION 3: ORDERS TABLE COMMENTS
-- =============================================================================

COMMENT ON TABLE orders IS
  'One order per buyer-vendor pair per checkout session. '
  'Financial records — never hard-deleted. '
  'buyer_id and vendor_id use ON DELETE RESTRICT.';

COMMENT ON COLUMN orders.order_number IS
  'Human-readable reference in format PS-ORD-XXXXXX. '
  'Auto-generated by the set_order_number trigger on INSERT.';
COMMENT ON COLUMN orders.buyer_id IS
  'FK to users(id) — the buyer who placed the order. '
  'ON DELETE RESTRICT: buyer accounts with orders cannot be deleted.';
COMMENT ON COLUMN orders.vendor_id IS
  'FK to users(id) — the vendor fulfilling the order. '
  'ON DELETE RESTRICT: vendor accounts with orders cannot be deleted.';
COMMENT ON COLUMN orders.status IS
  'Order lifecycle state (order_status enum). '
  'Path: pending → confirmed → processing → shipped → delivered. '
  'Cancellation: any pre-shipped state → cancelled.';
COMMENT ON COLUMN orders.subtotal IS
  'Sum of (unit_price × quantity) for all line items, before tax and shipping. '
  'Display via formatINR() — never render the raw decimal directly.';
COMMENT ON COLUMN orders.gst_amount IS
  'Total GST collected for this order. Sum of order_items.gst_amount.';
COMMENT ON COLUMN orders.total_amount IS
  'Grand total: subtotal + gst_amount + shipping_amount.';
COMMENT ON COLUMN orders.shipping_address IS
  'Snapshot of delivery address at checkout time. '
  'Keys: name, line1, line2, city, state, pincode, phone.';
COMMENT ON COLUMN orders.billing_address IS
  'Snapshot of billing address. Defaults to shipping_address if not provided.';
COMMENT ON COLUMN orders.cancelled_reason IS
  'Reason text populated when status transitions to ''cancelled''.';
COMMENT ON COLUMN orders.delivered_at IS
  'Timestamp set by the API when the order status changes to ''delivered''.';


-- =============================================================================
-- SECTION 4: ORDERS TRIGGERS
-- =============================================================================

-- Trigger 1: Auto-generate order_number on INSERT if not provided
CREATE TRIGGER set_order_number
  BEFORE INSERT ON orders
  FOR EACH ROW
  EXECUTE FUNCTION generate_order_number();

-- Trigger 2: Keep updated_at current on every row change
CREATE TRIGGER set_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();


-- =============================================================================
-- SECTION 5: ORDER ITEMS TABLE
-- =============================================================================

CREATE TABLE order_items (
  -- -----------------------------------------------------------------------
  -- Identity
  -- -----------------------------------------------------------------------
  id             UUID           PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The parent order. Cascade-deletes items if the order is ever deleted
  -- (orders themselves are never deleted, but cascade is correct semantics
  -- for line items — they have no meaning without the parent order).
  order_id       UUID           NOT NULL REFERENCES orders(id) ON DELETE CASCADE,

  -- FK to the original product listing. RESTRICT prevents a vendor from
  -- deleting a product that appears in a completed order.
  product_id     UUID           NOT NULL REFERENCES products(id) ON DELETE RESTRICT,

  -- -----------------------------------------------------------------------
  -- Product snapshot columns
  -- Copied from the products row at the time the order is created.
  -- These values are IMMUTABLE after insert — they record what the buyer
  -- purchased, regardless of any subsequent edits to the product listing.
  -- See DESIGN DECISION 3 in the file header.
  -- -----------------------------------------------------------------------

  -- Product name at time of purchase.
  product_name   TEXT           NOT NULL,

  -- Vendor's SKU at time of purchase (may be NULL if product had no SKU).
  product_sku    TEXT,

  -- -----------------------------------------------------------------------
  -- Line item financials
  -- -----------------------------------------------------------------------

  -- Number of units ordered. Must be at least 1.
  quantity       INTEGER        NOT NULL CHECK (quantity > 0),

  -- Per-unit price in INR at the time of purchase (from pricing_tiers or
  -- base_price, whichever applied at the ordered quantity).
  unit_price     DECIMAL(10,2)  NOT NULL CHECK (unit_price > 0),

  -- GST rate that applied to this product at time of purchase.
  gst_rate       DECIMAL(4,2)   NOT NULL,

  -- GST amount for this line: (unit_price × quantity) × (gst_rate / 100).
  gst_amount     DECIMAL(10,2)  NOT NULL,

  -- Line total inclusive of GST: (unit_price × quantity) + gst_amount.
  total_amount   DECIMAL(12,2)  NOT NULL,

  -- -----------------------------------------------------------------------
  -- Timestamps
  -- -----------------------------------------------------------------------
  created_at     TIMESTAMPTZ    DEFAULT NOW()
);


-- =============================================================================
-- SECTION 6: ORDER ITEMS TABLE COMMENTS
-- =============================================================================

COMMENT ON TABLE order_items IS
  'Line items for an order. Product name and SKU are snapshots captured at '
  'checkout — they do not change if the vendor later edits the product listing.';

COMMENT ON COLUMN order_items.order_id IS
  'FK to orders(id). Cascade-deletes with the parent order.';
COMMENT ON COLUMN order_items.product_id IS
  'FK to products(id). ON DELETE RESTRICT — products with order history '
  'cannot be deleted; vendor should deactivate instead.';
COMMENT ON COLUMN order_items.product_name IS
  'Snapshot of products.name at order creation time. Immutable after INSERT.';
COMMENT ON COLUMN order_items.product_sku IS
  'Snapshot of products.sku at order creation time. NULL if product had no SKU.';
COMMENT ON COLUMN order_items.unit_price IS
  'Per-unit price in INR at time of purchase, resolved from pricing_tiers or '
  'base_price. Immutable after INSERT.';
COMMENT ON COLUMN order_items.gst_rate IS
  'GST rate (%) that applied to this product at purchase time.';
COMMENT ON COLUMN order_items.gst_amount IS
  'GST amount for this line item: (unit_price × quantity) × (gst_rate / 100).';
COMMENT ON COLUMN order_items.total_amount IS
  'Line total inclusive of GST: (unit_price × quantity) + gst_amount.';


-- =============================================================================
-- SECTION 7: MESSAGES TABLE
-- =============================================================================

CREATE TABLE messages (
  -- -----------------------------------------------------------------------
  -- Identity
  -- -----------------------------------------------------------------------
  id          UUID         PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The user who sent the message. Cascade-deletes if the sender's account
  -- is removed — an inbox entry from a deleted user has no value.
  sender_id   UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- The intended recipient. Cascade-deletes if the recipient's account is
  -- removed for the same reason.
  receiver_id UUID         NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- Optional link to an order. SET NULL if the order is ever deleted so
  -- the message history is preserved even after the order is archived.
  -- NULL is valid for pre-sale enquiries that are not tied to any order.
  order_id    UUID         REFERENCES orders(id) ON DELETE SET NULL,

  -- -----------------------------------------------------------------------
  -- Content
  -- -----------------------------------------------------------------------

  -- Optional subject line — useful for the inbox list view.
  subject     TEXT,

  -- The message body. Required — a message without content is meaningless.
  content     TEXT         NOT NULL,

  -- Whether the receiver has opened/read this message.
  -- Used for the unread-count badge in the UI.
  is_read     BOOLEAN      DEFAULT FALSE,

  -- -----------------------------------------------------------------------
  -- Timestamps
  -- -----------------------------------------------------------------------
  created_at  TIMESTAMPTZ  DEFAULT NOW()
);


-- =============================================================================
-- SECTION 8: MESSAGES TABLE COMMENTS
-- =============================================================================

COMMENT ON TABLE messages IS
  'Buyer ↔ vendor inbox. Messages can be pre-sale enquiries (order_id NULL) '
  'or order-linked support messages (order_id set). '
  'Only the receiver can mark a message as read.';

COMMENT ON COLUMN messages.sender_id IS
  'FK to users(id). ON DELETE CASCADE — messages from deleted users are removed.';
COMMENT ON COLUMN messages.receiver_id IS
  'FK to users(id). ON DELETE CASCADE — messages to deleted users are removed.';
COMMENT ON COLUMN messages.order_id IS
  'Optional FK to orders(id). ON DELETE SET NULL — message history survives '
  'order deletion. NULL for pre-sale enquiries.';
COMMENT ON COLUMN messages.is_read IS
  'FALSE until the receiver opens the message. '
  'Drives the unread-message badge in the UI. '
  'Only the receiver may update this column (enforced by RLS).';


-- =============================================================================
-- SECTION 9: INDEXES
-- Ordered from most selective / highest traffic to supporting indexes.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Orders indexes
-- ---------------------------------------------------------------------------

-- Buyer dashboard: "My Orders" — primary access pattern for buyers
CREATE INDEX idx_orders_buyer_id
  ON orders(buyer_id);

-- Vendor order queue — primary access pattern for vendors
CREATE INDEX idx_orders_vendor_id
  ON orders(vendor_id);

-- Status filter — "Pending / In Progress / Completed" tabs on dashboards
CREATE INDEX idx_orders_status
  ON orders(status);

-- Order number lookup — used in search bars and deep-link URLs
CREATE INDEX idx_orders_order_number
  ON orders(order_number);

-- Default sort: newest orders first on all dashboard views
CREATE INDEX idx_orders_created_at
  ON orders(created_at DESC);

-- Payment status filter — finance/admin views
CREATE INDEX idx_orders_payment_status
  ON orders(payment_status);

-- ---------------------------------------------------------------------------
-- Order items indexes
-- ---------------------------------------------------------------------------

-- Load all items for a given order — used on every order detail page
CREATE INDEX idx_order_items_order_id
  ON order_items(order_id);

-- Look up all orders that include a specific product — used in vendor
-- product-performance reports and before product deletion checks
CREATE INDEX idx_order_items_product_id
  ON order_items(product_id);

-- ---------------------------------------------------------------------------
-- Messages indexes
-- ---------------------------------------------------------------------------

-- Sent messages — "Sent" tab in the messaging UI
CREATE INDEX idx_messages_sender_id
  ON messages(sender_id);

-- Inbox — "Received" tab in the messaging UI
CREATE INDEX idx_messages_receiver_id
  ON messages(receiver_id);

-- Messages linked to a specific order — order detail page conversation thread
CREATE INDEX idx_messages_order_id
  ON messages(order_id);

-- Default sort: newest message first in conversation threads
CREATE INDEX idx_messages_created_at
  ON messages(created_at DESC);

-- Partial index on unread messages only.
-- The unread badge query is: SELECT COUNT(*) FROM messages
--   WHERE receiver_id = $1 AND is_read = FALSE
-- A partial index covering only is_read = FALSE rows is far smaller and
-- faster than a full index on the boolean column.
CREATE INDEX idx_messages_unread
  ON messages(is_read)
  WHERE is_read = FALSE;


-- =============================================================================
-- SECTION 10: ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE orders      ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages    ENABLE ROW LEVEL SECURITY;


-- ---------------------------------------------------------------------------
-- ORDERS RLS POLICIES
-- ---------------------------------------------------------------------------

-- Policy 1: Buyers can view their own orders.
-- What it does: Allows SELECT on rows where buyer_id = the caller's auth UUID.
-- Why we need it: Buyers must see their purchase history on their dashboard.
CREATE POLICY "Buyers can view own orders"
  ON orders
  FOR SELECT
  USING ((select auth.uid()) = buyer_id);

-- Policy 2: Vendors can view orders assigned to them.
-- What it does: Allows SELECT on rows where vendor_id = the caller's auth UUID.
-- Why we need it: Vendors must see their order queue to process and fulfil orders.
CREATE POLICY "Vendors can view assigned orders"
  ON orders
  FOR SELECT
  USING ((select auth.uid()) = vendor_id);

-- Policy 3: Buyers can create new orders.
-- What it does: Allows INSERT when the new row's buyer_id = the caller's auth UUID.
-- Why we need it: Buyers place orders from the checkout page. The WITH CHECK
--               ensures a buyer cannot create an order on behalf of someone else.
CREATE POLICY "Buyers can create orders"
  ON orders
  FOR INSERT
  WITH CHECK ((select auth.uid()) = buyer_id);

-- Policy 4: Vendors can update status on their orders.
-- What it does: Allows UPDATE on rows where vendor_id = the caller's auth UUID.
-- Why we need it: Vendors must be able to confirm, ship, and mark orders delivered.
--               The API layer enforces which status transitions are valid and
--               prevents vendors from modifying financial columns.
CREATE POLICY "Vendors can update order status"
  ON orders
  FOR UPDATE
  USING     ((select auth.uid()) = vendor_id)
  WITH CHECK ((select auth.uid()) = vendor_id);

-- Policy 5: Admins have unrestricted access to all orders.
-- What it does: Allows ALL operations for users with role = 'admin' in users table.
-- Why we need it: Admins must be able to view, modify, and audit any order.
CREATE POLICY "Admins have full access to orders"
  ON orders
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE id = (select auth.uid())
        AND role = 'admin'
    )
  );


-- ---------------------------------------------------------------------------
-- ORDER ITEMS RLS POLICIES
-- ---------------------------------------------------------------------------

-- Policy 1: Users can view items belonging to their own orders.
-- What it does: Allows SELECT on order_items rows whose parent order has
--               the caller as either buyer or vendor.
-- Why we need it: Both parties to an order need to see the line items —
--               the buyer to review their purchase, the vendor to fulfil it.
--               The subquery hits the orders table which is already RLS-protected,
--               but we explicitly check buyer_id OR vendor_id here for clarity.
CREATE POLICY "Users can view items of their orders"
  ON order_items
  FOR SELECT
  USING (
    order_id IN (
      SELECT id FROM orders
      WHERE buyer_id  = (select auth.uid())
         OR vendor_id = (select auth.uid())
    )
  );

-- Policy 2: Admins have unrestricted access to all order items.
-- What it does: Allows ALL operations for admin users.
-- Why we need it: Admins audit order line items for dispute resolution and reporting.
CREATE POLICY "Admins have full access to order items"
  ON order_items
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE id = (select auth.uid())
        AND role = 'admin'
    )
  );


-- ---------------------------------------------------------------------------
-- MESSAGES RLS POLICIES
-- ---------------------------------------------------------------------------

-- Policy 1: Users can view messages they sent or received.
-- What it does: Allows SELECT on rows where sender_id = auth.uid() OR
--               receiver_id = auth.uid().
-- Why we need it: Users must see both their sent and received messages to
--               have a complete conversation view.
CREATE POLICY "Users can view messages they sent or received"
  ON messages
  FOR SELECT
  USING (
    (select auth.uid()) = sender_id
    OR
    (select auth.uid()) = receiver_id
  );

-- Policy 2: Users can send messages.
-- What it does: Allows INSERT when sender_id = the caller's auth UUID.
-- Why we need it: Any authenticated user (buyer or vendor) can initiate
--               a message. The WITH CHECK prevents spoofing the sender.
CREATE POLICY "Users can send messages"
  ON messages
  FOR INSERT
  WITH CHECK ((select auth.uid()) = sender_id);

-- Policy 3: Receivers can mark messages as read.
-- What it does: Allows UPDATE on rows where receiver_id = auth.uid().
-- Why we need it: Only the person who received a message should be able to
--               mark it as read. The API layer restricts which columns can
--               be updated (only is_read) — the RLS enforces who can do it.
CREATE POLICY "Receiver can mark messages as read"
  ON messages
  FOR UPDATE
  USING     ((select auth.uid()) = receiver_id)
  WITH CHECK ((select auth.uid()) = receiver_id);

-- Policy 4: Admins can view all messages.
-- What it does: Allows SELECT for admin users on every message row.
-- Why we need it: Admins monitor for abuse, resolve disputes, and audit
--               communication between buyers and vendors.
CREATE POLICY "Admins can view all messages"
  ON messages
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM users
      WHERE id = (select auth.uid())
        AND role = 'admin'
    )
  );
